# =============================================================================
# Layer 03-gitlab-config: GitLab CE Configuration
# =============================================================================
# Manages GitLab organizational structure: groups, projects, labels, branch
# protections, and CI/CD variables. Requires a running GitLab CE instance
# (deployed by Layer 03-core-infra + Ansible) and a PAT stored in Vault
# (generated by scripts/generate-gitlab-token.sh).
#
# Prerequisites:
#   - GitLab CE running at http://10.0.10.50
#   - PAT stored in Vault at secret/services/gitlab/admin
#   - Vault env vars set (VAULT_ADDR, VAULT_TOKEN, VAULT_CACERT)
#
# Usage:
#   cd terraform/layers/03-gitlab-config
#   terraform init
#   terraform apply                # reads PAT from Vault, no tfvars needed
#
# Emergency fallback (Vault unreachable):
#   terraform apply -var use_vault=false -var gitlab_token="glpat-xxxx"
# =============================================================================

terraform {
  required_version = ">= 1.9.0"

  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = ">= 17.8.0"
    }
    vault = {
      source  = "hashicorp/vault"
      version = ">= 4.0.0"
    }
  }
}
