---
# =============================================================================
# GitLab Role Handlers
# =============================================================================

- name: Reconfigure gitlab
  ansible.builtin.command:
    cmd: gitlab-ctl reconfigure
