---
# =============================================================================
# Mealie Role Handlers
# =============================================================================

- name: Restart mealie
  ansible.builtin.command:
    cmd: docker compose up -d --force-recreate
    chdir: "{{ mealie_install_dir }}"
